// Mocks generated by Mockito 5.4.4 from annotations
// in translite/test/features/translation/domain/usecases/translate_voice_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:translite/features/translation/domain/entities/language.dart'
    as _i5;
import 'package:translite/features/translation/domain/entities/translation_result.dart'
    as _i2;
import 'package:translite/features/translation/domain/repositories/translation_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTranslationResult_0 extends _i1.SmartFake
    implements _i2.TranslationResult {
  _FakeTranslationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TranslationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationRepository extends _i1.Mock
    implements _i3.TranslationRepository {
  MockTranslationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TranslationResult> translate(
    String? text,
    _i5.Language? source,
    _i5.Language? target,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #translate,
          [
            text,
            source,
            target,
          ],
        ),
        returnValue:
            _i4.Future<_i2.TranslationResult>.value(_FakeTranslationResult_0(
          this,
          Invocation.method(
            #translate,
            [
              text,
              source,
              target,
            ],
          ),
        )),
      ) as _i4.Future<_i2.TranslationResult>);

  @override
  _i4.Future<bool> isModelLoaded() => (super.noSuchMethod(
        Invocation.method(
          #isModelLoaded,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> loadModel() => (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unloadModel() => (super.noSuchMethod(
        Invocation.method(
          #unloadModel,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
